import type { Metadata } from "next";
import { Jomolhari } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu/Menu";

const jomolhari = Jomolhari({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gradient-to-tl from-[#9CB6EA] to-[#D5DBE2]">
      <body className={`${jomolhari.className} flex flex-row flex-nowrap h-full`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
